from __future__ import annotations

from pathlib import Path


def toml_string(value: str) -> str:
    if "\n" in value or '"' in value or "\\" in value:
        raise ValueError(f"cannot safely write TOML string: {value!r}")
    return f'"{value}"'


def write_ember_config(
    path: str | Path,
    *,
    run_id: str,
    model_path: str,
    tokenizer_path: str,
    prompts_path: str,
    output_dir: str,
    backend: str = "native",
    architecture: str = "qwen3",
    write_logits: bool = True,
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by Sarf Atlas.",
        "# Placeholder paths are allowed; replace them for local model runs.",
        f"run_id = {toml_string(run_id)}",
        f"model_path = {toml_string(model_path)}",
        f"architecture = {toml_string(architecture)}",
        f"tokenizer_path = {toml_string(tokenizer_path)}",
        f"backend = {toml_string(backend)}",
        'prompt_template = "{prompt}"',
        f"input_jsonl_path = {toml_string(prompts_path)}",
        f"output_dir = {toml_string(output_dir)}",
        "layers = []",
        'token_position = "prompt_final"',
        'sample_id_field = "id"',
        'word_field = "word"',
        "batch_size = 1",
        'dtype = "f32"',
        'output_format = "npy"',
        "prompt_hashes_only = false",
        f"write_logits = {str(write_logits).lower()}",
        "resume = false",
        "record_model_sha256 = false",
        "",
        "[run_metadata]",
        'workspace = "sarf-atlas"',
        'purpose = "Sarf v0.1 toy workflow config"',
        "toy = true",
        "no_generation = true",
        "no_hidden_states = true",
        "not_research_output = true",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
